Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xlsCH4 = pd.ExcelFile('GBR_2022_2020_10052022_142545.xlsx')
dfCH4 = pd.read_excel(xlsCH4, 'Table10s3', header=4)
dfCH4.set_index("GREENHOUSE GAS SOURCE AND SINK CATEGORIES", inplace=True)
dfCH4.dropna(inplace=True)

dfCH4.drop(
    labels = ["D.  Non-energy products from fuels and solvent use", "G.  Other product manufacture and use ", "C.  Rice cultivation", "D.  Agricultural soils", "E.  Prescribed burning of savannas", "F.  Other land", "E.  Other ","6.  Other (as specified in summary 1.A)", "International bunkers", "Navigation", "Multilateral operations",
 "Aviation"],
    axis=0,
    inplace = True
)
dfCH4.drop(
    labels = ["Base year(1)", "Change from base to latest reported year"],
    axis=1,
    inplace = True
)
#dfCH4
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m xlsCH4 [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mExcelFile[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mGBR_2022_2020_10052022_142545.xlsx[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m dfCH4 [38;5;241m=[39m pd[38;5;241m.[39mread_excel(xlsCH4, [38;5;124m'[39m[38;5;124mTable10s3[39m[38;5;124m'[39m, header[38;5;241m=[39m[38;5;241m4[39m)
[1;32m      3[0m dfCH4[38;5;241m.[39mset_index([38;5;124m"[39m[38;5;124mGREENHOUSE GAS SOURCE AND SINK CATEGORIES[39m[38;5;124m"[39m, inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py:1376[0m, in [0;36mExcelFile.__init__[0;34m(self, path_or_buffer, engine, storage_options)[0m
[1;32m   1374[0m     ext [38;5;241m=[39m [38;5;124m"[39m[38;5;124mxls[39m[38;5;124m"[39m
[1;32m   1375[0m [38;5;28;01melse[39;00m:
[0;32m-> 1376[0m     ext [38;5;241m=[39m [43minspect_excel_format[49m[43m([49m
[1;32m   1377[0m [43m        [49m[43mcontent_or_path[49m[38;5;241;43m=[39;49m[43mpath_or_buffer[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m
[1;32m   1378[0m [43m    [49m[43m)[49m
[1;32m   1379[0m     [38;5;28;01mif[39;00m ext [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1380[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1381[0m             [38;5;124m"[39m[38;5;124mExcel file format cannot be determined, you must specify [39m[38;5;124m"[39m
[1;32m   1382[0m             [38;5;124m"[39m[38;5;124man engine manually.[39m[38;5;124m"[39m
[1;32m   1383[0m         )

File [0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py:1250[0m, in [0;36minspect_excel_format[0;34m(content_or_path, storage_options)[0m
[1;32m   1247[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(content_or_path, [38;5;28mbytes[39m):
[1;32m   1248[0m     content_or_path [38;5;241m=[39m BytesIO(content_or_path)
[0;32m-> 1250[0m [38;5;28;01mwith[39;00m [43mget_handle[49m[43m([49m
[1;32m   1251[0m [43m    [49m[43mcontent_or_path[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[1;32m   1252[0m [43m[49m[43m)[49m [38;5;28;01mas[39;00m handle:
[1;32m   1253[0m     stream [38;5;241m=[39m handle[38;5;241m.[39mhandle
[1;32m   1254[0m     stream[38;5;241m.[39mseek([38;5;241m0[39m)

File [0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py:795[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    786[0m         handle [38;5;241m=[39m [38;5;28mopen[39m(
[1;32m    787[0m             handle,
[1;32m    788[0m             ioargs[38;5;241m.[39mmode,
[0;32m   (...)[0m
[1;32m    791[0m             newline[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m,
[1;32m    792[0m         )
[1;32m    793[0m     [38;5;28;01melse[39;00m:
[1;32m    794[0m         [38;5;66;03m# Binary mode[39;00m
[0;32m--> 795[0m         handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mhandle[49m[43m,[49m[43m [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m)[49m
[1;32m    796[0m     handles[38;5;241m.[39mappend(handle)
[1;32m    798[0m [38;5;66;03m# Convert BytesIO or file objects passed with an encoding[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'GBR_2022_2020_10052022_142545.xlsx'
FileNotFoundError: [Errno 2] No such file or directory: 'GBR_2022_2020_10052022_142545.xlsx'

